FROM sebp/elk:683
## Using default beats configuration
#ADD 02-beats-input.conf /etc/logstash/conf.d/02-beats-input.conf
ADD 12-json.conf /etc/logstash/conf.d/12-json.conf
ADD 30-output.conf /etc/logstash/conf.d/30-output.conf